### ISSUE TITLE
could you add more examples in the doc to show how to use your program?

### ISSUE THREAD

**Issue by neozhaoliang** [roice3/Honeycombs#1]
Hi Roice: the images in  your paper  seems fascinating, but how could other people reproduce them with this repo, especially render povray images of hyperboilc honeycombs? I hope you could add more explanations in README.md to show this, please do not assume all visitors are also C# programmers.

**Comment by roice3** [comment]
@neozhaoliang, thank you for the suggestion.  I will make this more friendly and add examples for reproducing the main set of images (the tables of the paper).  That will require offering a download as well, so visitors don't have to build anything.

I will think on how to make it more friendly for the POV-Ray functionality too, but am not promising anything.  I'm not assuming anything about visitors, but it takes much more energy and time to make user-friendly software than to simply share raw code folks can dig into.  I may not have the bandwidth/motivation to make POV-Ray functionality accessible to folks that don't have the bandwidth/motivation to dig into the code.  

Hopefully it will be easy to do a few simple things to expose some minimal POV-Ray capability, and I'll update this issue with progress.

**Comment by neozhaoliang** [comment]
I have been always wondering how you rendered images like this:

![h3_4333-0100_center_ultrawide](https://cloud.githubusercontent.com/assets/23307174/22184271/659da020-e109-11e6-81c9-9797a7d114d9.png)

could you explain this more in your doc?

**Comment by roice3** [comment]
Yes!  I can make all of the Wikipedia images more accessible.  It is some of the special one-off images in the paper that would be difficult to expose in a simple way, so thank you for the additional clarification.

I'm still planning to work on this request within the next few weeks by the way.

**Comment by roice3** [comment]
Hi @neozhaoliang, I've done some work to make things more friendly for UHS images.  The readme is updated and there is now a released version you can download to experiment with.  Let me know if you have suggestions on the path I took (editing a settings.xml file in the directory of the binary).  I'm hoping that will be friendly enough.

I'll tackle settings for the POV-Ray images next.

**Comment by neozhaoliang** [comment]
Hi Roice: I think this repo contains rather heavy math and it seems that you used some approximating algorithms in reflecting the fundamental domains in hyperbolic space. could you add a summary in each file that depict the intention of it? I'm a math Ph.D student and I found it hard to understand the logic of these many files.

**Comment by roice3** [comment]
Hi @neozhaoliang, I had written up a doc of useful functions for working in H^3 for another person, and I just added a link to it in the readme.  I hope it is helpful.

There are only two places I can think of where I use an "approximating algorithms".  

(1) For uniform honeycombs, I use an iterative method to find the vertex point in the simplex fundamental domain.  The function that does this attempts to converge to a point that will make all edge lengths the same.  That "IterateToStartingPoint" function is in the HoneycombGen.cs file.

(2) For determining how deep to recurse, I have some "CalcEdgesSmart" functions in Recurse.cs.  These functions do a couple smallish test recursions to estimate a threshold cutoff that will have an approximate number of edges for a much deeper recursion.

I don't use any approximating algorithm when doing the actual reflection of fundamental domains.  Let me know if you are looking at some other specific place that needs explanation.

Based on your comment above about the image you've wondered about, it sounds like HoneycombGen.cs is the main file that is relevant to you.  I've started work on settings for the POV-Ray images, and am doing some refactoring that I hope will also be helpful for clarity (basically moving a lot of outdated code out of HoneycombGen.cs - it will be about half the size).  

If you'd like to explain your goals more specifically, maybe I can help more.

**Comment by roice3** [comment]
Hi @neozhaoliang, I've finished up making the POV-Ray functionality more accessible, and used the honeycomb you referenced above as the sample.  See the readme updates for details.

The HoneycombGen code is refactored as well, and I hope it will be easier to follow.  I'm going to close this issue, but feel free to open other issues for clarification or any problems you see.  Thanks.

**Comment by neozhaoliang** [comment]
Hi Roice: I have seen another way of rendering honeycombs by the so called "distance estimation" which I don't understand much yet. Here is [an article by Jos Leys](http://images.math.cnrs.fr/La-methode-de-Newton-et-son-891.html?lang=fr) illustrates this approach.

There is an open source ray tracer [Fragmentarium](https://github.com/Syntopia/Fragmentarium) which has a [script](https://github.com/Syntopia/Fragmentarium/tree/master/Fragmentarium-Source/Examples/Knighty%20Collection/Hyperbolic-tesselations-named) implements this distance estimation method, it's code is rather different from yours. It seems that your approach requires more math knowledge and results in a larger .POV file.

you can see many examples in [this page](http://blog.hvidtfeldts.net/index.php/category/fragmentarium/page/2/). 

The author of the  Fragmentarium once said it's easy to translate these scripts into pov scene language files (but he did not do it). 

Just a mention of this, you have done a great work.

**Comment by roice3** [comment]
Thanks @neozhaoliang!  I wasn't aware of that article or those Fragmentarium scripts.

I have seen some folks use Fragmentarium and the "distance estimation" technique to great effect.  For example, check out images by [Abdelaziz Merzouk](https://plus.google.com/u/0/114982179961753756261).

I haven't taught myself this technique yet, but would like to learn.  It seems to have some real advantages over the POV-Ray approach (arbitrary rendering depth, no large files, quicker rendering times, etc.).

**Comment by neozhaoliang** [comment]
I found some useful sources for teaching oneself the DE trick, check [this blog](http://blog.hvidtfeldts.net/index.php/2011/06/distance-estimated-3d-fractals-part-i/) and [this one](http://iquilezles.org/www/index.htm).

Also there is a very down-to-earth article [here](http://jamie-wong.com/2016/07/15/ray-marching-signed-distance-functions/), which maybe you should read it first.

There are many GLSL fragment scripts that implements the DE method on [shadertoy](http://shadertoy.com), for example search for 'Klein' or 'Poincare' you will get a bunch of these.

-----

Here is another question:

I found your [soap bubble image](http://roice3.blogspot.com/2008/10/soap-bubbles.html) quite interesting, and as the image below:

![2017-03-04 10-56-44](https://cloud.githubusercontent.com/assets/23307174/23575588/2947863c-00ca-11e7-814f-933f2e176b05.png)
I'm trying to render the 120-cell with the same effect (see [wiki image](http://math.ucr.edu/home/baez/dodecahedron/32.html) ). I could compute all the vertices (in 4D sapce), edges and faces, but I don't know how to represent an edge in 3D (as a bending arc), and how to render a face as a soap bubble. 
Could you explain how you rendered it? or do  you have any exemplary POV-Ray scripts?
